#!/usr/bin/env bash
# client.sh - launch real VS Code on Xvfb and verify the remote workspace.
#
# Inputs:
# - /repo/scripts/cgenv is the read-only launcher from the current checkout.
# - /run/cgenv-smoke-keys/id_ed25519 is generated by server.sh.
# - CGENV_SMOKE_TIMEOUT_SECONDS bounds GUI and Remote - SSH startup.
#
# Outputs:
# - /tmp/cgenv-smoke-results contains the screenshot and assertion diagnostics
#   copied to .test-results/cgenv-smoke by tests/smoke/run.sh.
#
# Important behavior:
# - VS Code runs as an unprivileged Electron application on the Xvfb display.
# - The script closes the window and child processes on success or failure.
# - Private SSH key material is never copied into the result directory.

set -Eeuo pipefail

readonly RESULTS_DIR=/tmp/cgenv-smoke-results
readonly KEY_DIR=/run/cgenv-smoke-keys
readonly SSH_DIR=/home/vscode/.ssh
readonly TIMEOUT_SECONDS=${CGENV_SMOKE_TIMEOUT_SECONDS:-240}
readonly EXPECTED_VSCODE_VERSION=${CGENV_SMOKE_VSCODE_VERSION:?}
readonly EXPECTED_REMOTE_SSH_VERSION=${CGENV_SMOKE_REMOTE_SSH_VERSION:?}

xvfb_pid=
openbox_pid=
launcher_pid=
window_id=
window_title=
result=failed

mkdir -p "$RESULTS_DIR"
exec > >(tee -a "$RESULTS_DIR/client.log") 2>&1

log() {
	local level=$1
	local event=$2
	shift 2
	printf 'level=%s event=%s %s\n' "$level" "$event" "$*"
}

capture_diagnostics() {
	local -a window_ids=()

	ps -efww >"$RESULTS_DIR/processes.txt" 2>&1 || true

	if xdpyinfo -display "$DISPLAY" >/dev/null 2>&1; then
		xwininfo -root -tree >"$RESULTS_DIR/window-tree.txt" 2>&1 || true
		mapfile -t window_ids < <(
			xdotool search --onlyvisible --name CGENV_SMOKE 2>/dev/null
		)
		if [[ -z "$window_id" && ${#window_ids[@]} -gt 0 ]]; then
			window_id=${window_ids[0]}
		fi
		if [[ -n "$window_id" ]]; then
			xdotool getwindowname "$window_id" \
				>"$RESULTS_DIR/window-title.txt" 2>&1 || true
		fi
		scrot "$RESULTS_DIR/vscode.png" >/dev/null 2>&1 || true
	fi

	if [[ -d /home/vscode/.config/Code/logs ]]; then
		grep -R -n -E \
			'ssh-remote(\+|%2[Bb])ssh-server|SSH: ssh-server' \
			/home/vscode/.config/Code/logs \
			>"$RESULTS_DIR/remote-authority-matches.txt" 2>/dev/null \
			|| true
	fi
}

close_processes() {
	local attempt

	if [[ -n "$window_id" ]]; then
		xdotool windowclose "$window_id" >/dev/null 2>&1 || true
		for attempt in {1..10}; do
			xdotool getwindowname "$window_id" >/dev/null 2>&1 || break
			sleep 1
		done
	fi

	pkill -TERM -u "$(id -u)" -x code >/dev/null 2>&1 || true
	if [[ -n "$launcher_pid" ]]; then
		kill "$launcher_pid" >/dev/null 2>&1 || true
		wait "$launcher_pid" >/dev/null 2>&1 || true
	fi
	if [[ -n "$openbox_pid" ]]; then
		kill "$openbox_pid" >/dev/null 2>&1 || true
		wait "$openbox_pid" >/dev/null 2>&1 || true
	fi
	if [[ -n "$xvfb_pid" ]]; then
		kill "$xvfb_pid" >/dev/null 2>&1 || true
		wait "$xvfb_pid" >/dev/null 2>&1 || true
	fi
}

on_exit() {
	local status=$?

	trap - EXIT
	set +e
	capture_diagnostics
	printf 'status=%s\nexit_code=%s\n' "$result" "$status" \
		>"$RESULTS_DIR/result.env"
	close_processes
	log info client_cleanup "status=completed result=$result exit_code=$status"
	exit "$status"
}

fail() {
	log error assertions "status=failed reason=$1"
	exit 1
}

remote_authority_is_logged() {
	[[ -d /home/vscode/.config/Code/logs ]] \
		&& grep -R -E -q \
			'ssh-remote(\+|%2[Bb])ssh-server|SSH: ssh-server' \
			/home/vscode/.config/Code/logs 2>/dev/null
}

remote_server_is_running() {
	# VS Code 1.134 names its Node process MainThread, so match its command line.
	ssh ssh-server \
		'test -d "$HOME/.vscode-server" \
			&& ps -u "$(id -u)" -o args= \
				| grep -Eq "[.]vscode-server/.*/server/out/server-main[.]js .*--start-server"' \
		>/dev/null 2>&1
}

find_remote_window() {
	local candidate
	local candidate_title
	local -a visible_windows=()

	mapfile -t visible_windows < <(
		xdotool search --onlyvisible --name CGENV_SMOKE 2>/dev/null
	)
	for candidate in "${visible_windows[@]}"; do
		candidate_title=$(
			xdotool getwindowname "$candidate" 2>/dev/null || true
		)
		if [[ "$candidate_title" == *CGENV_SMOKE* \
			&& "$candidate_title" == *'/workspace'* ]]; then
			window_id=$candidate
			window_title=$candidate_title
			return 0
		fi
	done

	return 1
}

trap on_exit EXIT

log info client_setup 'status=started display=:99'

[[ "$TIMEOUT_SECONDS" =~ ^[1-9][0-9]*$ ]] \
	|| fail invalid_timeout_seconds

install -d -m 0700 "$XDG_RUNTIME_DIR" "$SSH_DIR"
install -m 0600 "$KEY_DIR/id_ed25519" "$SSH_DIR/id_ed25519"

for attempt in {1..20}; do
	if ssh-keyscan -T 3 -t ed25519 ssh-server \
		>"$SSH_DIR/known_hosts" 2>"$RESULTS_DIR/ssh-keyscan.log" \
		&& [[ -s "$SSH_DIR/known_hosts" ]]; then
		break
	fi
	if [[ $attempt -eq 20 ]]; then
		fail ssh_host_key_unavailable
	fi
	sleep 1
done
chmod 0600 "$SSH_DIR/known_hosts"

cat >"$SSH_DIR/config" <<'EOF'
Host ssh-server
    HostName ssh-server
    User smoke
    IdentityFile /home/vscode/.ssh/id_ed25519
    IdentitiesOnly yes
    BatchMode yes
    StrictHostKeyChecking yes
    UserKnownHostsFile /home/vscode/.ssh/known_hosts
    LogLevel ERROR
EOF
chmod 0600 "$SSH_DIR/config"

ssh ssh-server \
	'grep -Fq "CGENV Remote SSH smoke workspace" /workspace/README.md' \
	|| fail ssh_preflight_failed
log info ssh_preflight 'status=passed target=ssh-server workspace=/workspace'

code --version >"$RESULTS_DIR/vscode-version.txt"
IFS= read -r actual_vscode_version <"$RESULTS_DIR/vscode-version.txt"
[[ "$actual_vscode_version" == "$EXPECTED_VSCODE_VERSION" ]] \
	|| fail vscode_version_mismatch

code --list-extensions --show-versions \
	>"$RESULTS_DIR/extensions.txt"
grep --fixed-strings --line-regexp --quiet \
	"ms-vscode-remote.remote-ssh@${EXPECTED_REMOTE_SSH_VERSION}" \
	"$RESULTS_DIR/extensions.txt" \
	|| fail remote_ssh_version_mismatch
log info client_versions \
	"status=passed vscode=$EXPECTED_VSCODE_VERSION remote_ssh=$EXPECTED_REMOTE_SSH_VERSION"

Xvfb "$DISPLAY" -screen 0 1440x900x24 -nolisten tcp -noreset \
	>"$RESULTS_DIR/xvfb.log" 2>&1 &
xvfb_pid=$!
for attempt in {1..20}; do
	if xdpyinfo -display "$DISPLAY" >/dev/null 2>&1; then
		break
	fi
	if [[ $attempt -eq 20 ]]; then
		fail xvfb_start_failed
	fi
	sleep 1
done

openbox >"$RESULTS_DIR/openbox.log" 2>&1 &
openbox_pid=$!

log info launcher 'status=started target=ssh-server workspace=/workspace'
PATH=/opt/cgenv-smoke/bin:$PATH \
	/repo/scripts/cgenv ssh-server /workspace \
	>"$RESULTS_DIR/launcher.log" 2>&1 &
launcher_pid=$!

readonly deadline=$((SECONDS + TIMEOUT_SECONDS))
while ((SECONDS < deadline)); do
	if find_remote_window \
		&& remote_authority_is_logged \
		&& remote_server_is_running; then
		break
	fi

	if [[ -n "$launcher_pid" ]] && ! kill -0 "$launcher_pid" 2>/dev/null; then
		set +e
		wait "$launcher_pid"
		launcher_status=$?
		set -e
		launcher_pid=
		if [[ $launcher_status -ne 0 ]]; then
			fail launcher_failed
		fi
	fi

	sleep 2
done

[[ -n "$window_id" ]] || fail vscode_window_missing
window_title=$(xdotool getwindowname "$window_id" 2>/dev/null || true)
[[ "$window_title" == *CGENV_SMOKE* \
	&& "$window_title" == *'/workspace'* ]] \
	|| fail remote_workspace_title_missing
remote_authority_is_logged || fail remote_authority_missing
remote_server_is_running || fail remote_server_missing

timeout 20 code --status >"$RESULTS_DIR/code-status.txt" 2>&1 || true
ssh ssh-server \
	'printf "vscode_server_dir=%s\n" "$HOME/.vscode-server"; \
		ps -u "$(id -u)" -o pid=,comm=,args= \
			| grep -E "[.]vscode-server/"' \
	>"$RESULTS_DIR/remote-server-processes.txt"

result=passed
log info assertions \
	'status=passed window=visible authority=ssh-server workspace=/workspace server=running'
exit 0
